### ISSUE TITLE
macos requires zeromq

### ISSUE THREAD

**Issue by homephree** [akabe/ocaml-jupyter#135]
`ocaml install Jupyter` produces errors, finishing with:

`The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:`
    `zeromq`

```
caml 4.08.1
macOS 0.15.3 Beta
home-brew 2.2.3
```

fixed by `brew install zeromq` before `Ocaml install Jupiter`

Rather obvious fix, then it works fine.

Thanks - great project!

**Comment by akabe** [comment]
Linux also requires libzmq. I think the error message is easy to solve.

Regards,

**Comment by jeanas** [comment]
Well, for me it was not that easy to solve because `opam install jupyter` throwed a compilation error for onf-zmq ("No file 'zmq.h' found") but no message about the missing dependency, making me despair before eventually understanding what was going on.
I think it would be better to warn about the dependency.

**Comment by akabe** [comment]
Sorry for late reply. `opam depext jupyter` shows dependencies in major OS or distribution. If you need an error message in the build phase, I think you should open an issue about conf-zmq in https://github.com/ocaml/opam-repository. I will write dependencies in README, but exhaustive explanation is impossible because the names of packages are different every OS.
