### ISSUE TITLE
archimedes no longer installs (camlp4 obsolete)

### ISSUE THREAD

**Issue by curtosis** [akabe/ocaml-jupyter#153]
Following the instructions (to install archimedes and jupyter-archimedes) no longer works. It appears that archimedes requires camlp4, which is obsolete.

**Comment by akabe** [comment]
camlp4 is surely obsolete, but available. I can install camlp4, archimedes and jupyter-archimedes 2.7.2. If you failed to install them, please show me the error message you got.

**Comment by gorgeousNicko** [comment]
[archimedes.0.4.19] found in cache
[cairo2.0.6.1] found in cache
[camlp4.4.10+system] found in cache
[jupyter-archimedes.2.7.2] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of camlp4 failed at "/Users/nicksherrard/.opam/opam-init/hooks/sandbox.sh build sh ./make.sh".
[ERROR] The compilation of cairo2 failed at "/Users/nicksherrard/.opam/opam-init/hooks/sandbox.sh build dune build -p cairo2 -j 3".

#=== ERROR while compiling camlp4.4.10+system =================================#
# context     2.0.7 | macos/x86_64 | ocaml-system.4.10.0 | https://opam.ocaml.org#3c21183b
# path        ~/.opam/default/.opam-switch/build/camlp4.4.10+system
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh ./make.sh
# exit-code   1
# env-file    ~/.opam/log/camlp4-43669-60459a.env
# output-file ~/.opam/log/camlp4-43669-60459a.out
### output ###
# preexisting installation rather than compile one from scratch).
# [...]
# If you cannot install a system-wide camlp4, then you can still use OCaml
# 4.02 by switching to a local installation via `opam switch 4.02.0`.
# 
# Here are some installation instructions for camlp4 if you obtained OCaml
# via the OPAM binary packages:
# 
# http://software.opensuse.org/download.html?project=home%3Aocaml&package=ocaml
# 
# * Debian/Ubuntu: sudo apt-get install camlp4-extra
# * RHEL/CentOS/Fedora: sudo yum install ocaml-camlp4
#

**Comment by gorgeousNicko** [comment]
I am having essentially the same problem. It appears I am being told that installation of camlp4 requires camlp4! Here is the entire dialogue:

sudo opam install camlp4
[WARNING] Running as root is not recommended
The following actions will be performed:
  ∗ install camlp4 4.10+system

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[camlp4.4.10+system] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of camlp4 failed at "/Users/<name>/.opam/opam-init/hooks/sandbox.sh build sh ./make.sh".

#=== ERROR while compiling camlp4.4.10+system =================================#
# context     2.0.7 | macos/x86_64 | ocaml-system.4.10.0 | https://opam.ocaml.org#3c21183b
# path        ~/.opam/default/.opam-switch/build/camlp4.4.10+system
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh ./make.sh
# exit-code   1
# env-file    ~/.opam/log/camlp4-44215-1872ec.env
# output-file ~/.opam/log/camlp4-44215-1872ec.out
### output ###
# preexisting installation rather than compile one from scratch).
# [...]
# If you cannot install a system-wide camlp4, then you can still use OCaml
# 4.02 by switching to a local installation via `opam switch 4.02.0`.
# 
# Here are some installation instructions for camlp4 if you obtained OCaml
# via the OPAM binary packages:
# 
# http://software.opensuse.org/download.html?project=home%3Aocaml&package=ocaml
# 
# * Debian/Ubuntu: sudo apt-get install camlp4-extra
# * RHEL/CentOS/Fedora: sudo yum install ocaml-camlp4
# 



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build camlp4 4.10+system
└─ 
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    camlp4

# Run eval $(opam env) to update the current shell environment

**Comment by akabe** [comment]
@gorgeousNicko I think your error message is not related to ocaml-jupyter kernel and archimedes package. I recommend to open an issue at https://github.com/ocaml/opam-repository/issues .
