### ISSUE TITLE
Use with binder

### ISSUE THREAD

**Issue by edmcman** [akabe/ocaml-jupyter#158]
I made a [repo](https://github.com/edmcman/ocaml-jupyter-binder-environment) to show how to use `ocaml-jupyter` with [binder](https://www.mybinder.org).  It's as simple as "click here" to open up a jupyter notebook.

**Comment by mseri** [comment]
Thank you very much! This would be useful to have described in the README imo

**Comment by edmcman** [comment]
Thanks @mseri that's what I was thinking.  There are a few things to consider:

- We could incorporate this into the `ocaml-jupyter` repository itself.  But binder requires Dockerfiles to be in the root directory.  But we could have a branch dedicated for the binder Dockerfile.

- I noticed that some features do not work (like `#thread`).  Maybe this is because I'm not using the datascience Docker images as a base?

**Comment by akabe** [comment]
Thank you!

> We could incorporate this into the ocaml-jupyter repository itself. But binder requires Dockerfiles to be in the root directory. But we could have a branch dedicated for the binder Dockerfile.

I think it is better to split the ocaml-jupyter repository and your binder+ocaml-jupyter repository. As @mseri said, please explain about how to use ocaml-jupyter with binder in README. 

> I noticed that some features do not work (like #thread). Maybe this is because I'm not using the datascience Docker images as a base?

`#use "topfind"` is required before `#thread`. topfind is loaded in the `~/.ocamlinit` file in many environments, so that I don't write it explicitly in my notebooks. `RUN echo '#use "topfind";;' > /home/opam/.ocamlinit` solves your problem.

**Comment by edmcman** [comment]
Thanks, `topfind` was indeed the problem.  I filed a pull request (#159).

**Comment by akabe** [comment]
Merged #159.
