### ISSUE TITLE
Switch to jbuilder from oasis

### ISSUE THREAD

**Issue by rgrinberg** [akabe/ocaml-jupyter#63]
Hi!

You have a new and very exciting project here. But since it's so new, I'm wondering why you decided to use oasis over jbuilder. Jbuilder has many benefits over oasis (like far faster builds for example), so I'm wondering if there are any deficiencies to it in your view or you simply haven't gotten around to it.

**Comment by akabe** [comment]
@rgrinberg Thanks for suggestion, but migration to jbuilder is not an important issue for me: this project is not huge (like Jane Street Core) and the build is not so slow. Sub-directories and better namespace wrapping seem useful. I think priority of this issue is low, but I plan it when major refactoring (the code of this project is too complex).

**Comment by akabe** [comment]
Hmm. Maybe this is good timing for refactoring. OK, I try to switch to jbuilder. Thanks!

**Comment by rgrinberg** [comment]
Thank you! A release with this change would be nice as well.
