### ISSUE TITLE
Syntax highlight in lists

### ISSUE THREAD

**Issue by cprieto** [akabe/ocaml-jupyter#80]
I have no idea if this is a bug related to the Jupyter kernel or CodeMirror (Jupyter JS syntax highlight lib).

In a list, the first element is never highlighted, or every other element is highlighted, for example:

```ocaml
[2 ; 4; 5]
```

Highlights 2 and 3, but not 1 (see attachment)

<img width="1134" alt="screen shot 2017-12-06 at 13 27 11" src="https://user-images.githubusercontent.com/94194/33661667-3d7906aa-da89-11e7-8718-7788b34b3dda.png">

This only happens with numbers, not other type.

This behaviour happens in the akabe/iocaml:latest docker image

**Comment by akabe** [comment]
This is a bug of CodeMirror's ocaml mode. It has many highlight bugs, e.g.,

![codemirror-bug](https://user-images.githubusercontent.com/6229475/33663097-e7b47346-dad1-11e7-8ee0-1f810afb7a55.png)

I tried fixing them, but I gave up because the bug is not critical and it is boring work for me.

BTW, `akabe/iocaml` docker image is deprecated because IOCaml seems no longer maintained. I recommend (akabe/ocaml-jupyter-datascience)[https://github.com/akabe/docker-ocaml-jupyter-datascience]. There is no minimum Docker image for OCaml Jupyter yet, while I plan to create it.

**Comment by cprieto** [comment]
Thanks, let me see if I can go and see what is the problem with CodeMirror (I am mostly a JS dev getting into OCaml).

I can see as well if I would be able to do something with the Docker image, I made one from scratch to myself (mostly because right now I am in a house with a very bad internet connection so I need a slim image instead of an over 1GB full blown image).

Thanks a lot.

**Comment by akabe** [comment]
I have a faint memory, while there are two ways for fixing highlight bug:

1. Directly fix [CodeMirror/mllike/mllike.js](https://github.com/codemirror/CodeMirror/blob/master/mode/mllike/mllike.js): this is a file for highlight of ML-family languages, e.g., OCaml, F-sharp, SML. Maybe it is hard to support full OCaml syntax, thinking compatibility with other languages, but many OCaml programmers using CodeMirror become happy! 
2. Install a customized highlight JS file to Jupyter and specify the customized mode from OCaml Jupyter kernel (cf. [jupyter/src/core/shell.ml](https://github.com/akabe/ocaml-jupyter/blob/master/jupyter/src/core/shell.ml#L159)). This way does not require a PR to CodeMirror, but installation step of OCaml Jupyter becomes complex due to addition of a customized highlight script.

I don't remember the details, sorry.

I will publish a small Docker image for OCaml Jupyter as soon as possible. I already have [akabe/ocaml](https://hub.docker.com/r/akabe/ocaml/), a minimum Docker image for OCaml. I plan to add jupyter and OCaml Jupyter to this image.

I keep this issue because other users possibly have the same question.

Thanks.

**Comment by cprieto** [comment]
The issue is reported now in CodeMirror https://github.com/codemirror/CodeMirror/issues/5113

**Comment by akabe** [comment]
Great! Thank you!

**Comment by cprieto** [comment]
Done, PR done in CodeMirror, now it is matter of wait for the merge and Jupyter to include it with CodeMirror (or patch the installation to support it).

**Comment by akabe** [comment]
Thanks for your fast work! I close this issue.

**Comment by akabe** [comment]
@cprieto I created minimum Docker images for OCaml Jupyter: https://github.com/akabe/docker-ocaml-jupyter
